name: e2e Tests

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    ci:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                # node-version: [12.x, 14/.x, 16.x]
                os: [ubuntu-latest]
                node-version: [14.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup node env
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: ${{ matrix.node }}
                  cache: "yarn"

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache node_modules
              uses: actions/cache@v2
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              run: yarn
            
            - name: Build 
              run: yarn build
            
            - name: Run e2e test
              run: yarn cypress:test
